name: EPG Grabber

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Todos los dias a las 05:00 (Europa/Madrid)

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Grab EPG data
        run: npm run grab -- --channels=sites/movistarplus.es/movistarplus.es.channels.xml --maxConnections=3 --days=2 --timeout=10000

      - name: Commit and push
        run: |
          git config user.name "epg-bot[bot]"
          git config user.email "41898282+epg-bot[bot]@users.noreply.github.com"
          git add -f guide.xml
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "[BOT] Update EPG guide"
          git push
